jobs:
  include:
   - language: python
     python:
       - "3.5"
     before_install:
       - cd ./web/backend
     install:
       - pip install -r requirements.txt
     script:
       - pytest
 
   - language: android
     android:
       components:
         - build-tools: 28.0.3
         - android-28
         - extra

   - language: node_js
     node_js:
       - "10.12.0"
     before_script:
       - npm install -g @angular/cli
       - npm install -g node-sass
     script:
       - cd ./web/frontend
       - npm install
       - ng build --prod --aot
       - ng test
