version: '3'

services:
  db:
    restart: always
    image: postgres
    volumes:
      - /var/lib/postgresql/data
  backend:
    restart: always
    build: ./web/backend
    env_file: .env
    environment:
      DEBUG: 'true'
    volumes:
      - ./web/backend:/code
      - backend:/www/static
    ports:
      - "8000:8000"
    command: bash -c "python3 manage.py collectstatic --no-input && python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
  frontend:
    restart: always
    build: ./web/frontend
    volumes:
      - ./web/frontend:/frontend
    ports:
      - "4200:4200"
    command: bash -c "ng serve --host 0.0.0.0 --disable-host-check"
  nginx:
    restart: always
    image: nginx
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - backend:/www/static
  redis:
    restart: always
    image: redis:latest
    volumes:
      - /data

volumes:
  backend:
