version: '3'

services:
  db:
    restart: always
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
  backend:
    restart: always
    build: ./web/backend/
    env_file: .env
    environment:
      DEBUG: 'False'
    volumes:
      - ./web/backend:/code
      - backend:/www/static
    ports:
      - "8000:8000"
    command: bash -c "python3 manage.py collectstatic --no-input && python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
  frontend:
    restart: always
    build: ./web/frontend/
    volumes:
      - ./web/frontend:/frontend
    ports:
      - "4200:4200"
    command: bash -c "ng build --prod --base-href dist"
  nginx:
    restart: always
    build: 
      context: ./nginx/
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - backend:/www/static
  redis:
    restart: always
    image: redis:latest
    volumes:
      - /data

volumes:
  backend:
